# Site Settings
title: "Oleksandr Sobol"
name: "Oleksandr Sobol"
description: "Full Stack & Backend Developer | PHP, Python, Go, JS, MySQL, Docker, Networking"
url: "https://osobol.com"
baseurl: ""
repository: "OleksSobol/olekssobol.github.io"

# Reading Files
include:
  - _pages
  - .htaccess
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown Processing
markdown: kramdown
highlighter: rouge

# SEO and Analytics
timezone: America/Los_Angeles
locale: "en-US"

# Author Profile
author:
  name: "Oleksandr Sobol"
  avatar: "/assets/images/avatar.png"
  bio: "Full Stack Developer at Abstract Software LLC • Ex-GlobalNet Backend & Network Engineer"
  location: "Yakima, WA"
  email: "oleks@osobol.com"
  phone: "(406) 580-6183"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/OleksSobol"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/olekssobol/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:oleks@osobol.com"
